name: quizzes
description: quizzes

version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  get_it: ^7.7.0
  easy_localization: ^3.0.5
  go_router: ^13.2.4

  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2

  dio: ^5.4.3+1
  logger: ^2.2.0
  connectivity_plus: ^6.0.2
  hive: ^2.2.3
  path_provider: ^2.1.3
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.0
  image_cropper: ^5.0.1
  google_fonts: ^6.2.1
  libphonenumber_plugin: ^0.3.3
  pin_code_fields: ^8.0.1
  file: ^7.0.0
  url_strategy: ^0.2.0
  flutter_portal: ^1.1.4
  flutter_native_splash: ^2.4.0
  browser_image_compression: ^1.0.6
  dotted_border: ^2.1.0
  desktop_drop: ^0.4.4
  mime: ^1.0.5
  particles_flutter: ^0.1.4
  simple_animations: ^5.0.2
  gap: ^3.0.1
  modal_bottom_sheet: ^3.0.0
    
  _iwu_pack: ^0.1.0+4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
