name: quizzes
description: quizzes

version: 1.0.5

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0 
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  path_provider: ^2.1.1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  modal_bottom_sheet: ^2.1.2
  google_fonts: ^6.1.0
  libphonenumber_plugin: ^0.3.3
  pin_code_fields: ^8.0.1
  file: ^7.0.0
  url_strategy: ^0.2.0
  flutter_portal: ^1.1.4
  flutter_native_splash: ^2.3.8
  browser_image_compression: ^1.0.6
  dotted_border: ^2.1.0
  desktop_drop: ^0.4.4
  mime: ^1.0.4
  particles_flutter: ^0.1.4
  simple_animations: ^5.0.2
  gap: ^3.0.1
    
  _iwu_pack: ^0.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
