name: quizzes
description: quizzes

version: 1.0.5

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0 
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0

  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  logger: ^1.3.0
  connectivity_plus: ^3.0.3
  hive: ^2.2.3
  flutter_secure_storage: ^8.0.0
  rxdart: ^0.27.7
  path_provider: ^2.0.14
  responsive_builder: ^0.6.4
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.4
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  flutter_keyboard_visibility: ^5.4.0
  modal_bottom_sheet: ^2.1.2
  overlay_support: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.3
  libphonenumber_plugin: ^0.3.1
  pin_code_fields: ^7.4.0
  file: ^6.1.4
  url_strategy: ^0.2.0
  flutter_portal: ^1.1.3
  flutter_native_splash: ^2.2.19
  browser_image_compression: ^1.0.5
  dotted_border: ^2.0.0+3
  desktop_drop: ^0.4.1
  mime: ^1.0.4
  particles_flutter: ^0.1.4
  simple_animations: ^5.0.0+3
    
  _imagineeringwithus_pack:
    path: ../imagineeringwithus_pack

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
